### ISSUE TITLE
Replace gulp-compass with gulp-sass

### ISSUE THREAD

**Issue by imperator99** [govCMS/govCMS8-core#4]
Hi,
I suggest replacing `gulp-compass` in the govcms-ui build workflow with `gulp-sass`. This replacement means that there is no need to install the ruby gems and the entire workflow can be enabled with `npm install` (assuming that the package.json is included).
I was able to replace `gulp-compass` with `gulp-sass` with no ill effects, and I didn't have to bother trying to install the ruby gems and get them to work.
Thanks,
Jesse.

**Comment by fribibb** [comment]
I believe the current build processes used for this was just copied from a old project. 
Long story short, this will be getting a new Gulp setup, which will also solve #3 
So far we've only been focused on the base distro, rather than the theme. I haven't yet looked over it but it's likely a lot about it could change over the next few weeks.

**Comment by imperator99** [comment]
Thanks for the info @fribibb.
I have a similar D8 theme using gulp and UI Kit 2 in [this repo](https://github.com/govau/message-lab-theme). Feel free to pillage.

**Comment by fribibb** [comment]
the gulp setup has been completely redone, including removing the need for Compass/Ruby.

**Comment by imperator99** [comment]
Thanks @fribibb I saw that and pulled back into mine.
Cheers,
Jesse.
